repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]
        stages: [push]
